---
title: "Homework 1: Map-making and Environmental Justice"
subtitle: "Mapping low-income households and proximity to superfund sites in Virginia"
author: "Courtney Lorey"
date: 2025-10-5
---

# Description

# Objective

# Load packages
```{r}
library(tidyverse)
library(sf)
library(here)
library(tmap)
```

# Import data

1. Load necessary packages, import the ejscreen data, filter to relevant locations (in this case state and county), and find averages within counties.  

```{r}
# read in geodatabase of EJScreen data at the Census Block Group level
ejscreen <- sf::st_read(here::here("eds223-hw1", "data", "ejscreen","EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb")) 

# filter to Virginia
virginia <- ejscreen %>%
  dplyr::filter(ST_ABBREV == "VA") 

# filter to Loudoun County
loudoun <- ejscreen %>%
  dplyr::filter(CNTY_NAME %in% c("Loudoun County"))

# find the average values for all variables within counties
virginia_counties <- aggregate(virginia, by = list(virginia$CNTY_NAME), FUN = mean)
```

# Visualize data


# Map interpretation 